name: check jobs output 
on:
  push:
    branches:
    - jobOutput
  pull_request:
    branches:
    - jobOutput
env:
  PSRULE_AZURE_BICEP_PATH: '/usr/local/bin/bicep'
  PSRULE_OUTPUT_JOBSUMMARYPATH: reports/summary.md
  PSRULE_EXECUTION_INVARIANTCULTURE: Warn
  PSRULE_OUTPUT_AS: Summary
  PSRULE_OUTPUT_FORMAT: Csv
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      uses: azure/CLI@v1.0.7
      with:
        inlineScript: |
          GITHUB_OUTPUT = $(echo "test=hello")
    - id: step2
      uses: azure/CLI@v1.0.7
      with:
        inlinescript: |
          GITHUB_OUTPUT = $(echo "test=world")
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
