name: check jobs output 
on:
  push:
    branches:
    - jobOutput
  pull_request:
    branches:
    - jobOutput
env:
  PSRULE_AZURE_BICEP_PATH: '/usr/local/bin/bicep'
  PSRULE_OUTPUT_JOBSUMMARYPATH: reports/summary.md
  PSRULE_EXECUTION_INVARIANTCULTURE: Warn
  PSRULE_OUTPUT_AS: Summary
  PSRULE_OUTPUT_FORMAT: Csv
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        #old version from July 2023 - didn't work
        #creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.PWD }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.PWD }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    - name: Checkout
      uses: actions/checkout@v3
      
    - id: step0
      uses: azure/CLI@v1.0.7
      with:
        inlineScript: |
          GITHUB_OUTPUT=$(az group list)
          echo "::set-output name=test::$GITHUB_OUTPUT"
          
    - id: step1
      uses: azure/CLI@v1.0.7
      with:
        inlineScript: |
          GITHUB_OUTPUT=$(echo "hello")
          echo "::set-output name=test::$GITHUB_OUTPUT"
    - id: step2
      uses: azure/CLI@v1.0.7
      with:
        inlinescript: |
          GITHUB_OUTPUT=$(echo "world")
          echo "::set-output name=test::$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
