name: Analyze templates
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  analyze_arm:
    name: Analyze templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Analyze Azure resources using PSRule for Azure
    - name: Analyze Azure template files
      uses: microsoft/ps-rule@v2.9.0
      continue-on-error: true
      with:
        modules: 'PSRule.Rules.Azure,PSRule.Monitor'
        outputFormat: Csv
        outputPath: reports/ps-rule-results.csv
